
spring:
  datasource:
    url: jdbc:mysql://ip:3306/mapiis_db
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: mapiis
server:
  port: 8080
